################################# Default configuration ###################
# provide your domain here
baseURL = "https://djoloftech.codeforsenegal.org/"
# theme
theme = "dot-hugo"
# site title
title = "Djolof Tech"
defaultContentLanguage = "fr"

# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Cartographie des acteurs du numérique au Sénégal"
author = "Code for Senegal"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#0336FF"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ############################## 
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/Code-for-Senegal/Djolof-Tech-Food"


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 1
copyright = "Copyright &copy; [Code for Senegal](https://github.com/Code-for-Senegal) 2021"

# banner
[Languages.fr.params.banner]
title = "Écosystème numérique"
subtitle = "Cartographie des acteurs du numérique au Sénégal"
bg_image = "images/banner.jpg"
placeholder = "Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé votre acteur?"
content = "Contactez-nous pour plus de détails sur les services"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 4
name = "acteurs"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Blog"
  url = "blogs"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Communauté"
  url = "communautes"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "École"
  url = "ecoles"
  weight = 3

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Livre"
  url = "livres"
  weight = 4

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Mooc"
  url = "moocs"
  weight = 5

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Open Source"
  url = "open-source"
  weight = 6

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Podcast"
  url = "podcasts"
  weight = 7

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Presse et Actualité"
  url = "presse-et-actualite"
  weight = 8

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Social Média"
  url = "social-media"
  weight = 9

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Start-up"
  url = "start-up"
  weight = 10

  [[Languages.fr.menu.main]]
  parent = "acteurs"
  name = "Youtubeur"
  url = "youtubeur"
  weight = 11

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 2
copyright = "Copyright &copy; [Code for Senegal](https://github.com/Code-for-Senegal) 2021"

# banner
[Languages.en.params.banner]
title = "Digital ecosystem"
subtitle = "Mapping, digital players in Senegal"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Contact us for more details on the services"
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight = 3


################################ Wolof Language ######################
[Languages.wo]
languageName = "Wo"
languageCode = "wo"
weight = 3
copyright = "Aarin &copy; [Code for Senegal](https://github.com/Code-for-Senegal) 2021"

# banner
[Languages.wo.params.banner]
title = "kourel Xarala You Bess"
subtitle = "Lonkoyoon, ligééykat xarala you bess si Senegaal"
bg_image = "images/banner.jpg"
placeholder = "Am laaj si ligééykat? Seetal fi"

# call to action
[Languages.wo.params.cta]
enable = true
title = "Giso sa laaj wala si ligééykat ?"
content = "Jëflante ak ñun"
# call to action button
[Languages.wo.params.cta.button]
enable = true
label = "Jëflante ak ñun"
link = "contact"


################## wolof navigation #################
[[Languages.wo.menu.main]]
name = "Dalal ak jàmm"
url = "/"
weight = 1

[[Languages.wo.menu.main]]
name = "Laajté"
url = "faq"
weight = 2

[[Languages.wo.menu.main]]
name = "Dëkkuwaayu"
url = "contact"
weight = 3
